baseURL: "https://emilljungberg.com/"
title: Emil Ljungberg
paginate: 5
theme: 
- PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: true
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon_io/favicon.ico"
    favicon16x16: "/favicon_io/favicon-16x16.png"
    favicon32x32: "/favicon_io/favicon-32x32.png"
    apple_touch_icon: "/favicon_io/apple-touch-icon.png"
    safari_pinned_tab: "/favicon_io/apple-touch-icon.png"

  label:
    text: "Home"
    icon: /letter_logo.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: emil ljungberg
    subtitle: "Post hoc, ergo propter hoc"
    imageUrl: "/profile_pic.jpg"
    imageWidth: 180
    imageHeight: 180
    imageTitle: profile pic
    buttons:
      - name: Posts
        url: posts
      - name: Research
        url: research

  # home-info mode
  homeInfoParams:
    Title: "Emil Ljungberg"
    Content: Post hoc, ergo propter hoc

  socialIcons:
    - name: twitter
      url: "https://twitter.com/e_youngberg"
    - name: github
      url: "https://github.com/emilljungberg"
    - name: linkedin
      url: "https://www.linkedin.com/in/emilljungberg/"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=2U6CHHUAAAAJ&hl=en"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # editPost:
    # URL: "https://github.com/<path_to_repo>/content"
    # Text: "Suggest Changes" # edit text
    # appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: archive
      name: archive
      url: /archives/
      weight: 20
    - identifier: research
      name: research
      url: /research/
      weight: 30
    - identifier: about
      name: about
      url: /about/
      weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
